// import type { Metadata } from "next";
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<header className='flex bg-gray-100 border-b border-gray-300 p-4'>
					<div className='w-36  flex justify-between items-center mr-8'>
						<img src='https://upload.wikimedia.org/wikipedia/commons/d/d4/Rickandmortylogoru.png' />
					</div>
					<div className='flex justify-between items-center gap-4'>
						<Link href={'/'} className='text-lg font-medium text-gray-700 hover:text-black'>
							Users
						</Link>
						<Link href={'/episode'} className='text-lg font-medium text-gray-700 hover:text-black'>
							Episodes
						</Link>
						<Link href={'/location'} className='text-lg font-medium text-gray-700 hover:text-black'>
							Locations
						</Link>
					</div>
				</header>
				<main className='container mx-auto p-4'>{children}</main>
				{/* <footer>
					<footer>футер</footer>
				</footer> */}
			</body>
		</html>
	);
}
